services:
  vbcd-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    environment:
      SERVER_PORT: 8080
      DB_HOST: postgis
      DB_PORT: 5432
      DB_NAME: voxel_change_detection
      DB_USER: voxel
      DB_PASSWORD: voxel
      VOXELIZER_MOCK_EXECUTION: "true"
      VOXELIZER_STORAGE_ROOT: /data
      VOXELIZER_TEMP_PATH: /data/temp
      VOXELIZER_VISUALIZATION_TILES_PATH: /data/3dtiles
      VOXELIZER_VOXEL_SET_OUTPUT_PATH: /data/voxelsets
      VOXELIZER_JAR_PATH: /app/mago-voxelizer.jar
      VOXELIZER_DEFAULT_CREATE_MAX_LEVEL: 15
      VOXELIZER_DEFAULT_DIFF_MAX_LEVEL: 15
      VOXELIZER_DEFAULT_DIFF_DIFF_NEIGHBOR_MODE: 6
      VOXELIZER_DEFAULT_DIFF_MIN_DIFF_FILTER_LEVEL: 12
      VOXELIZER_DEFAULT_DIFF_MIN_DIFF_NEIGHBORS: 3
      VOXELIZER_DEFAULT_DIFF_DIFF_NEIGHBOR_ITERATIONS: 2
      VOXELIZER_DEFAULT_DIFF_MIN_DIFF_CLUSTER_SIZE: 20
    ports:
      - "8080:8080"
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - backend-storage:/data

  postgis:
    image: postgis/postgis:16-3.4
    container_name: backend-postgis
    environment:
      POSTGRES_DB: voxel_change_detection
      POSTGRES_USER: voxel
      POSTGRES_PASSWORD: voxel
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voxel -d voxel_change_detection"]
      interval:  10s
      timeout: 5s
      retries: 5
    volumes:
      - postgis-data:/var/lib/postgresql/data

volumes:
  postgis-data:
  backend-storage:
