"""initial schema

Revision ID: 34e6fb337834
Revises: 
Create Date: 2026-05-28 09:00:29.884382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e6fb337834'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('camera_lon', sa.Float(), nullable=False),
    sa.Column('camera_lat', sa.Float(), nullable=False),
    sa.Column('camera_height', sa.Float(), nullable=False),
    sa.Column('mesh_z_offset', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_dates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('date_code', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('mesh_path', sa.Text(), nullable=True),
    sa.Column('point_cloud_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date_code', name='uq_site_date')
    )
    op.create_index(op.f('ix_survey_dates_site_id'), 'survey_dates', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_dates_site_id'), table_name='survey_dates')
    op.drop_table('survey_dates')
    op.drop_table('sites')
    # ### end Alembic commands ###
