voxelizer:
  jar-path: C:/Workspace/git-repositories/geo-data-cube/mago-voxelizer/dist/mago-voxelizer-0.1.0-beta.jar
  storage-root: H:/workspace/change-detection
  mock-execution: false
  temp-path: H:/workspace/change-detection/temp
  visualization-tiles-path: H:/workspace/change-detection/3dtiles
  voxel-set-output-path: H:/workspace/change-detection/voxelsets
